spring.application.name=ProvaJava0804
spring.datasource.url=jdbc:postgresql://localhost:5432/provajava
spring.datasource.username=postgres
spring.datasource.password=BeachUP2026@

spring.session.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true